#cloud-config
ssh_pwauth: false
package_update: true

users:
- name: ${ansible_user}
  gecos: Ansible User
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - "${ansible_public_key}"
packages:
- git
write-files:
- path: /root/puppetrepo
  owner: root:root
  permissions: 700
  defer: true
  content: ${puppetrepo}
runcmd:
- cd /root
- git clone "${bootstraprepo}"
- cd ${bootstrapdir}
- bash ./deploy.sh
  